# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/constraints/KC705_constraints.xdc

# IP: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/vio_mmcm/vio_mmcm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_mmcm || ORIG_REF_NAME==vio_mmcm} -quiet] -quiet

# IP: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/mmcm_sys_clk/mmcm_sys_clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm_sys_clk || ORIG_REF_NAME==mmcm_sys_clk} -quiet] -quiet
