# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/constraints/KC705_physical.xdc

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/constraints/KC705_clocking.xdc

# IP: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/mmcm_sys_clk_wiz/mmcm_sys_clk_wiz.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm_sys_clk_wiz || ORIG_REF_NAME==mmcm_sys_clk_wiz} -quiet] -quiet
