set_property SRC_FILE_INFO {cfile:/home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/constraints/KC705_physical.xdc rfile:../../../../../sources/constraints/KC705_physical.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports {clk_sys_in_diff[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports {clk_sys_in_diff[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y23 [get_ports clk_sys_out]
