# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/trans_wiz/trans_wiz.xci
# IP: The module: 'trans_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/trans_wiz/trans_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_wiz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/trans_wiz/trans_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/trans_wiz/trans_wiz.xci
# IP: The module: 'trans_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/trans_wiz/trans_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fma_smits/documents/UU_afstuderen/VHDL_UU_KC705/sources/ip/trans_wiz/trans_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
